spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "https://eurika-service-production.up.railway.app"
              - "https://config-service-production-f025.up.railway.app"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders:
              - "*"
            allowCredentials: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST
      routes:
        - id: account-management-service
          uri: lb://ACCOUNTMANAGEMENT-SERVICE
          predicates:
            - Path=/account-management/**
          filters:
            - StripPrefix=1


        - id: batch-service
          uri: lb://BATCH-SERVICE
          predicates:
            - Path=/batch/**
          filters:
            - StripPrefix=1
            - AuthenticationFilter

        - id: cmi-service
          uri: lb://CMI-SERVICE
          predicates:
            - Path=/cmi/**
          filters:
            - StripPrefix=1
            - AuthenticationFilter

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notifications/**
          filters:
            - StripPrefix=1
            - AuthenticationFilter

        - id: transaction-service
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/transactions/**
          filters:
            - StripPrefix=1
            - AuthenticationFilter

        - id: portefeuille-service
          uri: lb://PORTEFEUILLE-SERVICE
          predicates:
            - Path=/portefeuille/**
          filters:
            - StripPrefix=1
            - AuthenticationFilter
      

  eureka:
    client:
      service-url:
        defaultZone: https://eurika-service-production.up.railway.app/eureka/
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/

